spring.application.name=ntt_customers
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

lombok.experimental.superBuilder=true

spring.r2dbc.url=r2dbc:postgresql://172.24.253.109:5432/postgres

spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20
spring.r2dbc.pool.max-idle-time=30m

spring.rabbitmq.host=localhost
spring.rabbitmq.username=vcjimenez
spring.rabbitmq.password=admin

spring.cloud.function.definition=sendCustomerRef

spring.cloud.stream.bindings.sendCustomerRef-in-0.destination=customer_exchange
spring.cloud.stream.bindings.sendCustomerRef-in-0.group=account_customer_queue
spring.cloud.stream.rabbit.bindings.sendCustomerRef-in-0.consumer.bindQueue=true
spring.cloud.stream.rabbit.bindings.sendCustomerRef-in-0.consumer.declareExchange=true
spring.cloud.stream.rabbit.bindings.sendCustomerRef-in-0.consumer.queueNameGroupOnly=true

spring.cloud.stream.bindings.emitRequestStatusAccount-out-0.destination=customer_exchange

