spring.application.name=ntt_custommrss
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/ntt_bank
spring.datasource.username=postgres
spring.datasource.password=postgres
lombok.experimental.superBuilder=true
spring.rabbitmq.host=localhost
spring.rabbitmq.username=vcjimenez
spring.rabbitmq.password=admin

spring.cloud.function.definition=customerResponseConsumer
spring.cloud.stream.bindings.customerResponseConsumer-in-0.destination=bank-ntt.response_queue
spring.cloud.stream.bindings.customerResponseConsumer-in-0.group=customer-service-group

spring.cloud.stream.rabbit.bindings.customerResponseConsumer-in-0.consumer.requeue-rejected=false
