SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE DATABASE ntt_bank WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';
ALTER DATABASE ntt_bank OWNER TO postgres;

\connect ntt_bank

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.customer (
    id bigint NOT NULL,
    address character varying(255),
    age integer,
    gender character varying(255),
    id_number character varying(255),
    name character varying(255),
    phone character varying(255),
    password character varying(255),
    status boolean
);

ALTER TABLE public.customer OWNER TO postgres;

CREATE TABLE public.account (
    id bigint NOT NULL,
    customer_ref bigint,
    status boolean,
    num_account bigint,
    initial_funds numeric(38,2),
    account_type character varying(255)
);

ALTER TABLE public.account OWNER TO postgres;

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.movement (
    id bigint NOT NULL,
    "date" date,
    balance numeric(38,2),
    type_movement character varying(255),
    uuid character varying(255),
    "value" numeric(38,2),
    account_movement bigint
);

ALTER TABLE public.movement OWNER TO postgres;

ALTER TABLE public.movement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('public.account_id_seq', 14, true);
SELECT pg_catalog.setval('public.movement_id_seq', 27, true);

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.customer
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.account
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.movement
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE ONLY public.account
    ADD CONSTRAINT ukn106vdgjiivvhg0vilxnfvk2s UNIQUE (num_account);

ALTER TABLE ONLY public.movement
    ADD CONSTRAINT fk63txaglddp738qnb5uhtd1a4w FOREIGN KEY (account_movement) REFERENCES public.account(id);